// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	Avatar       string
	Skin         pgtype.Text
	Cloak        pgtype.Text
	RegisteredAt pgtype.Timestamptz
	IsActive     bool
}
