// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, 
    email, 
    password_hash, 
    avatar, 
    skin, 
    cloak, 
    registered_at, 
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Avatar       string
	Skin         pgtype.Text
	Cloak        pgtype.Text
	RegisteredAt pgtype.Timestamptz
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
		arg.Skin,
		arg.Cloak,
		arg.RegisteredAt,
		arg.IsActive,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    username,
    email,
    avatar,
    skin,
    cloak,
    registered_at,
    is_active
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	Username     string
	Email        string
	Avatar       string
	Skin         pgtype.Text
	Cloak        pgtype.Text
	RegisteredAt pgtype.Timestamptz
	IsActive     bool
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Skin,
		&i.Cloak,
		&i.RegisteredAt,
		&i.IsActive,
	)
	return i, err
}

const updateUserCloak = `-- name: UpdateUserCloak :exec
UPDATE users 
SET cloak = $1 
WHERE id = $2
`

type UpdateUserCloakParams struct {
	Cloak pgtype.Text
	ID    uuid.UUID
}

func (q *Queries) UpdateUserCloak(ctx context.Context, arg UpdateUserCloakParams) error {
	_, err := q.db.Exec(ctx, updateUserCloak, arg.Cloak, arg.ID)
	return err
}

const updateUserSkin = `-- name: UpdateUserSkin :exec
UPDATE users 
SET skin = $1 
WHERE id = $2
`

type UpdateUserSkinParams struct {
	Skin pgtype.Text
	ID   uuid.UUID
}

func (q *Queries) UpdateUserSkin(ctx context.Context, arg UpdateUserSkinParams) error {
	_, err := q.db.Exec(ctx, updateUserSkin, arg.Skin, arg.ID)
	return err
}
