// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :many
INSERT INTO users (
    username, 
    email, 
    password_hash, 
    avatar, 
    skin, 
    cloak, 
    registered_at, 
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	Avatar       string
	Skin         pgtype.Text
	Cloak        pgtype.Text
	RegisteredAt pgtype.Timestamptz
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
		arg.Skin,
		arg.Cloak,
		arg.RegisteredAt,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT 
    username,
    email,
    avatar,
    skin,
    cloak,
    registered_at,
    is_active
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	Username     string
	Email        string
	Avatar       string
	Skin         pgtype.Text
	Cloak        pgtype.Text
	RegisteredAt pgtype.Timestamptz
	IsActive     bool
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.Skin,
		&i.Cloak,
		&i.RegisteredAt,
		&i.IsActive,
	)
	return i, err
}
